In [11]:
#import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [12]:
# Loading the dataset
data = pd.read_csv('IRIS.csv')

# printing rows and columns of datset
print(data.head())
print(data.info())


   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [13]:
#Separate the features (sepal and petal measurements) and the target variable (species)
X = data.drop('species', axis=1)  # Features
y = data['species']              # Target variable

In [14]:
#splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)


In [15]:
#scaling the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [16]:
# training rhe model using KNN(K-NEAREST-NEIGHBOR)
knn = KNeighborsClassifier(n_neighbors=3)  # You can experiment with different values of K
knn.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=3)

In [17]:
y_pred = knn.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)


Accuracy: 0.9833333333333333
Confusion Matrix:
 [[23  0  0]
 [ 0 19  0]
 [ 0  1 17]]
Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        23
Iris-versicolor       0.95      1.00      0.97        19
 Iris-virginica       1.00      0.94      0.97        18

       accuracy                           0.98        60
      macro avg       0.98      0.98      0.98        60
   weighted avg       0.98      0.98      0.98        60



In [18]:
# Use the model to classify a new iris flower
new_flower = [5.1, 3.5, 1.4, 0.2]
new_flower = np.reshape(new_flower, (1, 4))
prediction = knn.predict(new_flower)
print('The flower is classified as:', prediction)

The flower is classified as: ['Iris-virginica']
